name: MMOperms
version: 1.0
main: arcane.luckpermsrefresh.plugin.RefreshProfilePerms
api-version: 1.21
depend: [MMOProfiles, LuckPerms, Vault]
commands:
  mmoperm:
    description: Adds a permission via Vault and LuckPerms
    usage: /mmoperm <uuid> add <permission>
  listprofiles:
     description: Check player profile's UUID
     usage: /listprofiles <name>
